# Generated by Django 2.1.1 on 2018-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('value', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Значение ключа')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Не выдан'), (1, 'Выдан'), (2, 'Погашен')], db_index=True, default=0, verbose_name='Статус ключа')),
            ],
        ),
        migrations.CreateModel(
            name='NewKeysCounter',
            fields=[
                ('table_name', models.CharField(default='main_key', max_length=255, primary_key=True, serialize=False)),
                ('new_keys', models.PositiveIntegerField(default=0, verbose_name='Счётчик новых не выданных ключей')),
            ],
        ),
    ]
