# coding: utf-8
# Generated by Django 2.1.1 on 2018-09-25 13:06
import io
import itertools
import time

from django.db import connection, migrations


def generate_keys(apps, schema_editor):
    """
    Заполняем БД ключами.
    При 62 различных символах и длинне ключа в 4 символа, ключей должно нагенериться 14 776 336
    """

    def save_to_db(data):
        data.seek(0)
        with connection.cursor() as cursor:
            cursor.copy_from(data, Key._meta.db_table, columns=('value', 'status'))

    Key = apps.get_model('main', 'Key')

    letters_upper = [
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
        'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
        'U', 'V', 'W', 'X', 'Y', 'Z'
    ]
    letters_lower = [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
        'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
        'u', 'v', 'w', 'x', 'y', 'z'
    ]
    digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    all_symbols = letters_upper + letters_lower + digits

    start = time.time()
    batch_size = 100000     # Кол-во ключей, которые мы передаём в БД за один раз.
                            # Ограничение установлено, чтобы python не проглотил всю память.

    all_keys_gen = itertools.product(''.join(all_symbols), repeat=4)

    try:
        while True:
            data = io.StringIO()
            counter = 0

            while True:
                data.write(
                    "{0}\t0\n".format(
                        ''.join(next(all_keys_gen))
                    )
                )
                counter += 1

                if counter == batch_size:
                    save_to_db(data)
                    break

    except StopIteration:
        # StopIteration возникает, когда заканиваются значения в генераторе all_keys_gen
        save_to_db(data)

    end = time.time()
    print('\nВремя выполнения: ', end - start)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_keys)
    ]
