# Generated by Django 2.1.1 on 2018-09-25 13:31

from django.db import migrations, connection


def block_deleting_and_inserting(apps, schema_editor):
    if connection.vendor == 'postgresql':
        Key = apps.get_model('main', 'Key')
        cursor = connection.cursor()
        cursor.execute('''
            CREATE FUNCTION block_delete_and_insert() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Deleting or inserting keys is prohibited';
                END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER block_delete_and_insert_trigger BEFORE DELETE OR INSERT ON {keys_table_name}
                FOR EACH ROW EXECUTE PROCEDURE block_delete_and_insert();
        '''.format(keys_table_name=Key._meta.db_table))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_generate_keys'),
    ]

    operations = [
        migrations.RunPython(block_deleting_and_inserting)
    ]
