# coding: utf-8
# Generated by Django 2.1.1 on 2018-09-25 13:34

from django.db import migrations


def insert_counter_initial_value(apps, schema_editor):
    """
    Кол-во доступных для выдачи ключей храниться в отдельной таблице модели NewKeysCounter
    """
    Key = apps.get_model('main', 'Key')
    NewKeysCounter = apps.get_model('main', 'NewKeysCounter')

    new_keys_amount = Key.objects.filter(status=0).count()
    NewKeysCounter.objects.create(
        table_name=Key._meta.db_table,
        new_keys=new_keys_amount
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_block_deleting_and_inserting'),
    ]

    operations = [
        migrations.RunPython(insert_counter_initial_value)
    ]
