# coding: utf-8
# Generated by Django 2.1.1 on 2018-09-25 13:40

from django.db import migrations, connection


def add_counter_trigger(apps, schema_editor):
    """
    Добавляет триггер, который при смене статуса ключа (с нового на выданный) уменьшает
    счётчик новых ключей на единицу.
    """
    if connection.vendor == 'postgresql':
        NewKeysCounter = apps.get_model('main', 'NewKeysCounter')
        cursor = connection.cursor()
        cursor.execute('''
            CREATE FUNCTION update_counter() RETURNS trigger AS $$
                BEGIN
                    IF NEW.status != 0 AND OLD.status = 0 THEN
                        EXECUTE
                        'UPDATE {counter_table_name}
                        SET new_keys=new_keys-1
                        WHERE table_name = \'\'\' || TG_TABLE_NAME || \'\'\' ';
                    END IF;
                    RETURN NEW;
                END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER update_counter_trigger AFTER UPDATE ON main_key
                FOR EACH ROW EXECUTE PROCEDURE update_counter();
        '''.format(counter_table_name=NewKeysCounter._meta.db_table))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_insert_counter_initial_value'),
    ]

    operations = [
        migrations.RunPython(add_counter_trigger)
    ]
